[package]
name = "dmap"
description = "Parse and serialize Apple's DMAP format."
license = "MIT"
version = "0.2.0"
authors = ["main() <main@ehvag.de>"]

[dependencies]
byteorder = "1.0"
serde = "1.0"
serde_derive = "1.0"
